= Akka Streams


include::partial$include.adoc[]


{akka}/stream/stream-introduction.html[Akka Streams {tab-icon}, window="tab"] provides an intuitive and safe way to formulate stream processing setups such that we can then execute them efficiently and with bounded resource usage —- no more OutOfMemoryErrors.

The Akka Streams API is completely decoupled from the xref:reactive-streams.adoc[] interfaces. While Akka Streams focus on the formulation of transformations on data streams the scope of Reactive Streams is to define a common mechanism of how to move data across an asynchronous boundary without losses, buffering or resource exhaustion.

The relationship between Akka Streams and Reactive Streams is that the Akka Streams API is geared towards end-users while the Akka Streams implementation uses the Reactive Streams interfaces internally to pass data between the different operators. What this means is that you can implement an application where Akka Streams interconnect with other Reactive Streams implementations in a fully compatible way.

== Learn more

To learn more, have a look at the {akka}/stream/stream-introduction.html[Akka Streams documentation {tab-icon}, window="tab"] dedicated sections:

* Read the {akka}/stream/stream-quickstart.html[Quick Start Guide {tab-icon}, window="tab"] to get a feel for how streams look like and what they can do.
* Read the {akka}/general/stream/stream-design.html[Design Principles behind Akka Streams {tab-icon}, window="tab"] for a top down learning approach.
* Have a look at the {akka}/stream/operators/index.html[operator index {tab-icon}, window="tab"] for a complete overview of the built-in processing operators.
* Check the {akka}/stream/stream-flows-and-basics.html[reference guide {tab-icon}, window="tab"] for an in-depth documentation into specific topics.
