= Akka Projections


include::partial$include.adoc[]



In Akka Projections you process a stream of events or records from a source to a projected model or external system. Each event is associated with an offset representing the position in the stream. This offset is used for resuming the stream from that position when the projection is restarted.

Akka Projections tackles the following challenges:

* Implement the read-side of a xref:cqrs.adoc[CQRS system].
* Ensure reliable delivery of events to external consumers in face of network errors and system crashes.

NOTE: The xref:microservices-tutorial:index.adoc[Implementing Microservices with Akka tutorial] illustrates how to implement an Event Sourced CQRS application with Akka Projections and Akka Persistence. See for example the xref:microservices-tutorial:projection-query.adoc[] and the xref:microservices-tutorial:projection-kafka.adoc[] steps.

== Learn more

* The {akka-blog}/news/2020/09/10/akka-projection-intro-video[Introduction to Akka Projections video {tab-icon}, window="tab"] is a good starting point for learning Akka Projections.

* To know more, check the {akka-projection}[Akka Projections reference documentation {tab-icon}, window="tab"].
