= Concepts
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

include::partial$include.adoc[]

This section explains the concepts that motivate Akka's take on how to implement microservices using Event
Sourcing and CQRS. Microservices built using Event Sourcing and CQRS adhere to the properties of a
link:{reactive-manifesto}[Reactive System] and are often called Reactive Microsystems.

Read the xref:introduction-traditional-architecture.adoc[introduction] for an explanation of the motivation for
Reactive Microsystems, and a high level overview of the key concepts that power Reactive Microsystems.

== In-depth concepts

* xref:isolation.adoc[] and xref:autonomy.adoc[]


* xref:event-sourcing.adoc[]
* xref:internal-and-external-communication.adoc[]
* xref:cqrs.adoc[]

ifdef::todo[(TODO: this last item ("What makes up a service?") is out of place, needs a new section)]

* xref:services.adoc[]
** xref:service-discovery.adoc[]
** xref:service-clients.adoc[]
** xref:grpc-services.adoc[]

== Akka Overview

* xref:clustering.adoc[]

