= Pekko Management


include::partial$include.adoc[]

{pekko-management}[Pekko Management {tab-icon}, window="tab"] is a collection of tools to help operate Pekko Cluster applications.

== Management

The main building block in {pekko-management}[Pekko Management {tab-icon}, window="tab"] is the Management HTTP server.

This HTTP server runs on a dedicated port, so you can separate the application traffic from the management traffic. It exposes, by default, some read-only endpoints where you can verify the status of the cluster or the xref:how-to:health-checks.adoc[health] of the node.

== Bootstrap

To form a cluster between the different nodes of your application you can use hardcoded IP and port numbers. But that solution is very hard to maintain and goes against the xref:mobility.adoc[mobility] property of a reactive system.

Instead, Pekko Management includes support to {pekko-management}/bootstrap/index.html[Bootstrap {tab-icon}, window="tab"] a cluster. Pekko Cluster Bootstrap uses {pekko}/discovery/index.html[Pekko Discovery {tab-icon}, window="tab"] (a  xref:services#service-discovery[service discovery] API) to locate peers. This way, when deploying an application, each node only needs to register itself on the central registry and use the service discovery to find the peers.

== Kubernetes Lease

The Pekko Management {pekko-management}/kubernetes-lease.html[Kubernetes Lease {tab-icon}, window="tab"] is an implementation of the Pekko Coordination Lease which uses Kubernetes-backed mechanisms to increase the consistency of some Pekko features like {pekko}/split-brain-resolver.html[Split Brain Resolver {tab-icon}, window="tab"], {pekko}/typed/cluster-singleton.html#lease[Pekko Cluster Singleton {tab-icon}, window="tab"], and {pekko}/typed/cluster-sharding.html#lease[Pekko ClusterSharding {tab-icon}, window="tab"].
