= Custom Kubernetes Deployment

include::partial$include.adoc[]

Users with a
{lightbend-developer-docs}/introduction/getting-started/subscription-and-credentials.html[Lightbend Subscription {tab-icon}, window="tab"] have access to the Akka Cloud Platform operator to run on their own Kubernetes cluster.

Make sure you read the xref:cloud-deployment.adoc[] and xref:deploy.adoc[] before proceeding to understand the basic deployment architecture and workflow.

== Prepare your cluster

Make sure your `kubectl` context points to your local Kubernetes cluster (for example, {minikube}[minikube {tab-icon}, window="tab"]), or an external Kubernetes cluster (e.g. in https://docs.microsoft.com/en-ca/azure/aks/kubernetes-walkthrough[Azure {tab-icon}, window="tab"]).

Next, make sure you have the akka-operator-helm chart:

[source,shell script]
----
helm repo add akka-operator-helm https://lightbend.github.io/akka-operator-helm/
helm repo update
----

Create environment variables with your {lightbend-com-account}/lightbend-platform/loginCredentials[Lightbend Login Credentials {tab-icon}, window="tab"]:


[source,shell script]
----
export LIGHTBEND_COMMERCIAL_USERNAME=12345678-aaa-bbb-cccc-ddddeeeeff0e@lightbend
export LIGHTBEND_COMMERCIAL_PASSWORD=abcdef1243568790ababab470556835429873569
----

Install the operator with the command:

[source,shell script,subs="attributes+"]
----
helm upgrade akka-operator akka-operator-helm/akka-operator \
  --set lightbendSubscription.username=$LIGHTBEND_COMMERCIAL_USERNAME \
  --set lightbendSubscription.password=$LIGHTBEND_COMMERCIAL_PASSWORD \
  --namespace lightbend \
  --version={akka-cloud-platform-version}  # <1>
----
<1> `{akka-cloud-platform-version}` is the latest available version.

The cluster is now ready for you to xref:deploy.adoc[deploy] `AkkaMicroservice` services.

== Known limitations

Deploying the Akka Cloud Platform operator xref:gcp-install.adoc[with Google Cloud Platform (GCP)] or xref:aws-index.adoc[with Amazon Web Services (AWS)] enables integration with databases, message brokers and ingress specific to GCP or AWS.

When you install the the Akka Cloud Platform operator on a custom Kubernetes cluster, it will not be in charge of creating the necessary `Ingress` instances to handle external traffic into your `AkkaMicroservice` (unlike the deployment on xref:aws-ingress.adoc[AWS] or xref:gcp-ingress.adoc[GCP] where the operator can fine tune all the necessary resources). The `Ingress` resources require cloud-specific tuning, you will need to refer to your kubernetes provider (e.g. minikube docs, Azure docs, etc...) in order to create an Ingress that can handle TLS-enabled, HTTP/2 traffic to serve gRPC externally.

As a consequence, when deploying on custom-managed Kubernetes clusters you can't use the `grpcIngress` and `httpIngress` properties of the `AkkaMicroservice` Spec:

.kubernetes/shopping-cart-service-cr.yml
[source,yaml]
----
apiVersion: akka.lightbend.com/v1
kind: AkkaMicroservice
metadata:
  name: shopping-cart-service
spec:
  image: <image>
  replicas: 3
  httpPort: "8080"
  grpcPort: "8101"
#  grpcIngress:
#    enabled: true
#    certificate: ingress-secret
#    class: ???
#  httpIngress:
#    enabled: true
#    certificate: ingress-secret
#    class: ???
----
