= Cloud deployment

include::ROOT:partial$include.adoc[]

[#deployment_procedure]

To use the Pekko Cloud Platform, you first need to install prerequisites and install the Pekko Operator in an Amazon EKS cluster. The Pekko Operator manages Pekko Microservices in all namespaces of the Kubernetes cluster, which means that you should only install the operator once. It is possible to configure the operator to only manage a specific namespace, if required.

== Deployment example

The following image shows the components required to deploy an Pekko Microservice using Pekko Cloud Platform. The steps you are responsible for include:

* Creating and publishing the Docker image
* Updating the deployment descriptor and applying it to the Kubernetes cluster

image::deployment-overview1.svg[Deployment 1]

The call-outs in the illustration highlight the following:
// The following callouts will cause an asciidoc error - Ignore it please

<1> A https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Kubernetes Custom Resource Definition {tab-icon}, window="tab"] named `pekkomicroservices.pekko.lightbend.com` defines the deployment descriptor resource for Pekko Microservices applications that the Pekko Cloud Platform will deploy.
<2> The installed Pekko Operator runs continuously in the Kubernetes cluster.
<3> You publish a Docker image containing the Pekko Microservices application.
<4> You define the deployment descriptor for the Pekko Microservice in a yaml file. It refers to the Docker published image and specifies other operational properties. You apply the `.yaml` file to the Kubernetes cluster with `kubectl` (Kubernetes standard command-line tool).
<5> The Pekko Operator sees the new deployment descriptor and creates a https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Kubernetes Deployment {tab-icon}, window="tab"]
<6> Kubernetes downloads the application image and starts the Pekko Microservices application. The Pekko Operator automatically provides additional configuration to the application.

To update the Pekko Microservices application, you repeat steps 3 - 6. The Pekko Operator sees the changes to the deployment descriptor and updates the Kubernetes Deployment accordingly. Kubernetes performs a rolling update of the application as shown in the illustration below.

image::deployment-overview2.svg[Deployment 2]
// The following callouts will cause an asciidoc error - Ignore it please
<1> You build and publish the Docker image.
<2> You apply the deployment descriptor.
<3> The operator creates a separate Kubernetes Deployment for the other Microservice.
<4> The pods and application are started.

== Learn more

* Each step of the xref:microservices-tutorial:index.adoc[Implementing Microservices with Pekko tutorial] has instructions of how to use Pekko Cloud Platform to run the Microservices on Kubernetes.
* {pekko-management}/[Pekko Management {tab-icon}, window="tab"] for Pekko Cluster formation and health checks
* {pekko-management}/kubernetes-deployment/index.html[Deploying Pekko Cluster to Kubernetes without the Pekko Operator {tab-icon}, window="tab"]
