= Cloud deployment

include::ROOT:partial$include.adoc[]

[#deployment_procedure]

To use the Akka Cloud Platform, you first need to install prerequisites and install the Akka Operator in an Amazon EKS cluster. The Akka Operator manages Akka Microservices in all namespaces of the Kubernetes cluster, which means that you should only install the operator once. It is possible to configure the operator to only manage a specific namespace, if required.

== Deployment example

The following image shows the components required to deploy an Akka Microservice using Akka Cloud Platform. The steps you are responsible for include:

* Creating and publishing the Docker image
* Updating the deployment descriptor and applying it to the Kubernetes cluster

image::deployment-overview1.svg[Deployment 1]

The call-outs in the illustration highlight the following:
// The following callouts will cause an asciidoc error - Ignore it please

<1> A https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Kubernetes Custom Resource Definition {tab-icon}, window="tab"] named `akkamicroservices.akka.lightbend.com` defines the deployment descriptor resource for Akka Microservices applications that the Akka Cloud Platform will deploy.
<2> The installed Akka Operator runs continuously in the Kubernetes cluster.
<3> You publish a Docker image containing the Akka Microservices application.
<4> You define the deployment descriptor for the Akka Microservice in a yaml file. It refers to the Docker published image and specifies other operational properties. You apply the `.yaml` file to the Kubernetes cluster with `kubectl` (Kubernetes standard command-line tool).
<5> The Akka Operator sees the new deployment descriptor and creates a https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Kubernetes Deployment {tab-icon}, window="tab"]
<6> Kubernetes downloads the application image and starts the Akka Microservices application. The Akka Operator automatically provides additional configuration to the application.

To update the Akka Microservices application, you repeat steps 3 - 6. The Akka Operator sees the changes to the deployment descriptor and updates the Kubernetes Deployment accordingly. Kubernetes performs a rolling update of the application as shown in the illustration below.

image::deployment-overview2.svg[Deployment 2]
// The following callouts will cause an asciidoc error - Ignore it please
<1> You build and publish the Docker image.
<2> You apply the deployment descriptor.
<3> The operator creates a separate Kubernetes Deployment for the other Microservice.
<4> The pods and application are started.

== Learn more

* Each step of the xref:microservices-tutorial:index.adoc[Implementing Microservices with Akka tutorial] has instructions of how to use Akka Cloud Platform to run the Microservices on Kubernetes.
* {akka-management}/[Akka Management {tab-icon}, window="tab"] for Akka Cluster formation and health checks
* {akka-management}/kubernetes-deployment/index.html[Deploying Akka Cluster to Kubernetes without the Akka Operator {tab-icon}, window="tab"]
