= AWS LoadBalancer Controller
:page-toclevels: 3

include::partial$include.adoc[]

gRPC and HTTP ingress with the https://cloud.google.com/kubernetes-engine/docs/concepts/ingress[GKE Ingress Controller {tab-icon}, window="tab"] is supported
ion documentation {tab-icon}, window="tab"]

== Container native load balancing

Only https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing[container native load balancing {tab-icon}, window="tab"] is supported to allow a health check to access the Akka Management port
rather than the gRPC or HTTP ports.

When using HTTP if you override the readiness probe to a path on your HTTP port this will also be used for the load balancer health check.

== TLS certificate

You need a TLS certificate for the internet facing load balancer.

For development and test you can import a self signed certificate, which can be created with for example:

[source,shell script]
----
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:4096 -keyout dummy-key.pem -out dummy-cert.pem -subj "/CN=dummy/O=dummy"
----

// TODO support uploading to GCP as well
Create a secret for the certificate:

[source, shell script]
----
kubectl create secret tls ingress-secret  --cert dummy-cert.pem  --key dummy-key.pem
----

This is referenced from the Akka Microservice.

== Enable grpcIngress

Add the `grpcIngres` section to the deployment descriptor and `akka.lightbend.com/ingress-class` annotation set to `gce`:

.kubernetes/shopping-cart-service-cr.yml:
[source,yaml]
----
apiVersion: akka.lightbend.com/v1
kind: AkkaMicroservice
metadata:
  name: shopping-cart-service
  namespace: "shopping"
  annotations:
    akka.lightbend.com/ingress-class: gce
spec:
  image: <image>
  grpcIngress:
    enabled: true
    certificate: "<secret-name>"
----


When the deployment descriptor has been applied the Akka Operator will create an Ingress with the appropriate GKE annotations and `ClusterIp` service.

You can retrieve the public address with:

[source,shell script]
----
kubectl get ingress shopping-order-service-grpc-ingress
----

To access the public endpoint with grpcurl you use the public address from above, with port 443:

[source,shell script]
----
grpcurl -insecure -d '{"cartId":"cart3", "itemId":"hoodie", "quantity":2}' <ingress ip>:443 shoppingcart.ShoppingCartService.AddItem
----

You have to use the `-insecure` flag if the certificate is self signed.
