= Installation in Google Cloud Platform
:page-toclevels: 3

include::partial$include.adoc[]

To install Akka Cloud Platform on Google Kubernetes Engine (GKE), you must have a Google Cloud Platform account and a project.

== Deploy from marketplace

For first time GCP user, please register your Google account at https://console.cloud.google.com[https://console.cloud.google.com {tab-icon}, window="tab"].

Open the https://console.cloud.google.com/marketplace/details/lightbend-public/akka-cloud-platform[Akka Cloud Platform {tab-icon}, window="tab"] or search for "Akka Cloud Platform" in the https://console.cloud.google.com/kubernetes/application[Kubernetes Applications {tab-icon}, window="tab"]. Once in the product page, purchase a plan.

Once you've purchased a plan to use the Akka Cloud Platform, proceed to configure it. Make sure you have a project selected on the GUI or the options to purchase and configure will be disabled.

To completely configure and use the Akka Cloud Platform you need to set up a few fields:

. GKE cluster where you are installing the operator (or use the "Create a new cluster" is you still don't have one)
. Namespace: keeping the Marketplace offering in a specific namespace ease follow up operations and enforces separation of concerns
. App instance name: select a unique name. We recommend using the default or `akka-platform-operator-1`.
. akka-operator.serviceAccount.name: the name of the service account used by the operator to access Kubernetes resources
. Reporting Service Account: service account used for reporting data to Google

Finally, take a moment to review all the permissions the Akka Clout Platform operator will use in order to operate your applications.

Clink on the "Deploy".

== Delete a Kubernetes cluster

You can use the https://console.cloud.google.com/kubernetes/list[GCP GUI {tab-icon}, window="tab"] to delete the cluster.
