= GKE Ingress
:page-toclevels: 3

include::partial$include.adoc[]

gRPC and HTTP ingress with the https://cloud.google.com/kubernetes-engine/docs/concepts/ingress[GKE Ingress Controller {tab-icon}, window="tab"] is supported
ion documentation {tab-icon}, window="tab"]

== Container native load balancing

Exposing the Akka Management port, as opposed to the gRPC and HTTP ports, is only possible using the  https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing[container-native load balancing {tab-icon}, window="tab"].

If you override the readiness probe to a path on your HTTP port, this will also be used for the load balancer health check.

== TLS certificate

You need a TLS certificate for the internet facing load balancer. Akka gRPC also needs to be configured with a certificate as GKE ingress for HTTP/2 only works over SSL. This certificate can be any self signed certificate as no validation is done bewtween the loadbalancer the application. // TODO link to and improve the how-to on gRPC TLS

For development and test you can import a self signed certificate, which can be created with for example:

[source,shell script]
----
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:4096 -keyout dummy-key.pem -out dummy-cert.pem -subj "/CN=dummy/O=dummy"
----

// TODO support uploading to GCP as well
Create a secret for the certificate:

[source, shell script]
----
kubectl create secret tls ingress-secret  --cert dummy-cert.pem  --key dummy-key.pem
----

This is referenced from the Akka Microservice.

== Enable grpcIngress

Add the `grpcIngres` section to the deployment descriptor with class set to `gce`:

.kubernetes/shopping-cart-service-cr.yml:
[source,yaml]
----
apiVersion: akka.lightbend.com/v1
kind: AkkaMicroservice
metadata:
  name: shopping-cart-service
  namespace: "shopping"
  annotations:
spec:
  image: <image>
  grpcIngress:
    enabled: true
    certificate: "<secret-name>"
    class: "gce"
----


When the deployment descriptor has been applied the Akka Operator will create:

* An Ingress with the appropriate GKE annotations
* A `ClusterIP` service.
* A `BackendConfig' to configure a health check to match the readiness check

You can retrieve the public address with:

[source,shell script]
----
kubectl get ingress shopping-order-service-grpc-ingress
----

To access the public endpoint with grpcurl you use the public address from above, with port 443:

[source,shell script]
----
grpcurl -insecure -d '{"cartId":"cart3", "itemId":"hoodie", "quantity":2}' <ingress ip>:443 shoppingcart.ShoppingCartService.AddItem
----

You have to use the `-insecure` flag if the certificate is self signed.
