= Pekko Cloud Platform

include::partial$include.adoc[]

The Pekko Cloud Platform enables developers to quickly build and deploy cloud-native Microservices on their cloud service provider of choice. It provides frameworks and runtimes for building cloud-native applications that easily integrate with other services in your chosen ecosystem.

An Pekko Cloud Platform subscription includes access to Lightbend Telemetry, Lightbend Academy, and basic support. Through the Pekko Operator, the Pekko Cloud Platform provides the following high level features:

* Convenient deployment without the need to define detailed Kubernetes manifests
* Integration with Pekko Cluster Bootstrap
* Integration with Pekko Management health checks
* Integration with Relational Databases
* Integration with Cassandra
* Integration with Kafka
* Support for gRPC and HTTP services and internet-facing ingress
* Insights into deployment status

The Pekko Cloud Platform is currently available in xref:gcp-install.adoc[Google Cloud Platform (GCP)] and xref:aws-index.adoc[Amazon Web Services (AWS)]

== Getting Started with Cloud Deployment
Before you can get started with cloud deployment you should:

. Determine which platform you will be using (Google Cloud Platform, for example).
. Have an active account with your chosen platform.
. Subscribe to the Pekko Cloud Platform with xref:gcp-install.adoc[GCP] or xref:aws-index.adoc[AWS].
. Set up your xref:microservices-tutorial:dev-env.adoc[environment].

Once you have these in hand review the xref:cloud-deployment.adoc[] page and then proceed to the section appropriate to your platform.

* xref:gcp-install.adoc[]
* xref:aws-install.adoc[]

