= Integrations
:page-toclevels: 3

include::partial$include.adoc[]

Stateful services need a datastore. You can store state using xref:concepts:event-sourcing.adoc[Event Sourcing] or CRUD. The example in the tutorial uses PostgreSQL for xref:microservices-tutorial:entity.adoc[storing the events] and xref:microservices-tutorial:entity.adoc[and creating a Projection for queries]. An alternative is described in xref:how-to:cassandra-alternative.adoc[]

To decouple communication between different Microservices, we can publish messages to a broker, such as Apache Kafka. The tutorial illustrates how to use Apache Kafka in xref:microservices-tutorial:projection-kafka.adoc[Projection publishing to Kafka]. See xref:concepts:internal-and-external-communication.adoc[Internal and External Communication concepts] for more information.

== Data store integrations

The Akka Operator provides integrations with:

* xref:aws-rds.adoc[]
* xref:astra.adoc[]
* xref:cassandra.adoc[]

== Message broker integrations

The Akka Operator provides integrations with:

* xref:aws-msk.adoc[]
* xref:confluent-cloud.adoc[]
* xref:strimzi.adoc[]
