= Kafka - Strimzi operator
:page-toclevels: 3

include::partial$include.adoc[]

For production usage we recommend using xref:confluent-cloud.adoc[Confluent Cloud] (Cloud-Native Kafka-as-a-Service).

For development or test environments you may want to manage your own Kafka cluster with Strimzi.
https://strimzi.io/docs/operators/latest/using.html[Strimzi {tab-icon}, window="tab"] simplifies the process of running Apache Kafka in a Kubernetes cluster.

== Install Strimzi

[source,shell script]
----
kubectl create namespace akka-demo
----

Add the Strimzi Helm repository and update the local index.

[source,shell script]
----
helm repo add strimzi https://strimzi.io/charts/
helm repo update
----

Install the latest version of Strimzi.

[source,shell script]
----
helm install strimzi strimzi/strimzi-kafka-operator --namespace akka-demo
----

After the install completed, the Strimzi Kafka operator should be running in the given namespace.

[source,shell script]
----
kubectl config set-context --current --namespace=akka-demo
----

[source,shell script]
----
kubectl get pods
----

To create a Kafka cluster using Strimzi, create the custom resource for the Strimzi Kafka operator. See configuration options in the https://strimzi.io/docs/operators/latest/using.html[Strimzi documentation {tab-icon}, window="tab"].

[source,shell script]
----
kubectl apply -f kubernetes/strimzi-cr.yml
----

Retrieve the bootstrap address you can use to access the Kafka cluster from the status of the Kafka resource when all pods are ready:

[source,shell script]
----
kubectl describe kafka kafka-strimzi

kubectl get kafka kafka-strimzi -o=jsonpath='{.status.listeners[?(@.type=="plain")].bootstrapServers}{"\n"}'
----

== Create topic

The Strimzi operator can create topics from a `KafkaTopic` custom resource. See configuration options in the https://strimzi.io/docs/operators/latest/using.html[Strimzi documentation {tab-icon}, window="tab"].

[source,shell script]
----
kubectl apply -f kubernetes/strimzi-topic-cr.yml
----

== Configure connection

Define the connection details in a config file. Use the bootstrap servers retrieved above.

.kubernetes/strimzi-config.conf
[source,shell script]
----
# common config for akka.kafka.producer.kafka-clients and akka.kafka.consumer.kafka-clients
kafka-connection-settings {
  bootstrap.servers = "kafka-strimzi-kafka-bootstrap.akka-demo.svc:9092"
}
akka.kafka.producer {
  kafka-clients = ${kafka-connection-settings}
}
akka.kafka.consumer {
  kafka-clients = ${kafka-connection-settings}
}
----

Create the `strimzi-config` config secret from the config file:

[source,shell script]
----
kubectl create secret generic strimzi-config --from-file=kubernetes/strimzi-config.conf
----

Define the `configSecret` in the CR of the application:

[source,yaml]
----
apiVersion: akka.lightbend.com/v1
kind: AkkaMicroservice
metadata:
  name: shopping-cart-service
spec:
  image: <image>
  configSecret:
    secretName: strimzi-config
----

Apply the CR:

[source,shell script]
----
kubectl apply -f kubernetes/shopping-cart-service-cr.yml
----

The Akka Operator will automatically xref:config-secret.adoc#main-conf[provide the configuration] from the Secret when the application starts the `ActorSystem`.

== Uninstall Strimzi

If you want to remove Strimzi, you can do that with the following Helm command:

[source,shell script]
----
helm delete strimzi -n akka-demo
----
