= Akka Platform Guide
:description: Guided documentation of Akka for specific use cases

include::ROOT:partial$include.adoc[]

Welcome to the _Akka Platform Guide_!

Akka is a toolkit for building highly concurrent, distributed, and resilient message-driven applications.

Both beginners getting started with _Reactive_ principles and active Akka users will find this guide useful to improve their understanding of how Akka fits into _Reactive_ and how Reactive concepts apply to Akka. The guide complements the {akka}[Akka reference documentation {tab-icon}, window="tab"], which presents all Akka features in detail.

The tutorials in this guide show end-to-end use-cases implemented in Akka with the Reactive principles in mind. The tutorials go through implementing a system step-by-step to illustrate how the Akka APIs apply together.

== How to get the most out of this guide

For a code-first experience, have a look at the xref:microservices-tutorial:index.adoc[Implementing Microservices with Akka tutorial] which walks you through an example project and explains how features from the Akka ecosystem fit together to build Reactive Systems. The tutorial will point you to the relevant xref:concepts:index.adoc[concepts] where applicable.

If this is your first experience with Reactive frameworks or with Akka, we present some background and ideas behind _Reactive_ in the xref:concepts:index.adoc[Concepts section]. You can read those when they are introduced in the tutorial, or read them first if you prefer a more theoretical overview before diving into the code. There you will learn for example:

* The challenges that Reactive Architecture can help you overcome
* A summary of Reactive Principles
* The benefits of using Akka

== Key Information for Akka Cloud Platform on AWS
The links and info below provide rapid access to some of the more important information used to manage your Akka Cloud Platform.

- Kubernetes Akka Platform Operator — Operator management is key. You will find details on xref:deployment:aws-install.adoc[installing]
and xref:deployment:aws-install.adoc#_update_akka_operator[updating] the Akka Operator on the Installation in Amazon EKS page.

- TLS Certificates — TLS certificates are required for external access to applications managed by Akka Cloud Platform. You will find the pertinent information within the xref:deployment:aws-ingress.adoc#_tls_certificate[AWS LoadBalancer Controller] page.

- Support — Support for the Akka Cloud Platform requires registration. https://aws.amazon.com/marketplace/pp/B08TLV16XM#pdp-support[Details] regarding support, and more, can be found on the AWS Marketplace.

- License expiration and renewal — You may have purchased your license by subscribing to the Akka Cloud Platform product on the AWS Marketplace, or  directly from Lightbend. In either case, the license expiration and renewal for the Akka Cloud Platform is handled as follows:
* If the Akka Cloud Platform license expires without being renewed, your current application will continue to run, but you will no longer be able to deploy or update.
* If you have acquired a term license directly from Lightbend, and it expires, your license will automatically revert into a pay-as-you-go license.
* When you need to renew your license, please contact mailto:aws@lightbend.com[] with your request.

== Akka Microservices tutorial

The xref:microservices-tutorial:index.adoc[Implementing Microservices with Akka tutorial] illustrates how to implement an Event Sourced CQRS application with Akka Persistence and Akka Projections.

The tutorial shows how to build and run each service step by step:

include::microservices-tutorial:partial$listing.adoc[]

== Cloud deployment

Kubernetes has become the de facto platform for deploying in the cloud. The easiest way to deploy and manage Akka Microservices in Kubernetes is to use the Akka Cloud Platform, which is currently available for Amazon Web Services(AWS). The xref:deployment:index.adoc[Cloud deployment] section provides an overview of how the Kubernetes deployment with the Akka Cloud Platform works.

Each step of the tutorial has instructions of how to run in Kubernetes using the Akka Cloud Platform.

ifdef::review[REVIEWERS: I removed the link to the first step of the tutorial from here because it is a circular reference, that is, that page just links to another page in the deployment section.]

== How to...

Some development tasks arise from requirements on existing projects. The xref:how-to:index.adoc[] section collects guidance for how to introduce a new feature or architectural improvement on an existing codebase.

include::how-to:partial$listing.adoc[]


**This documentation was last published: {localdate}**
