= How to enable TLS for gRPC
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

include::partial$include.adoc[]

In the xref:shopping-microservices:index.adoc[Microservices Tutorial] there's a guide on creating a xref:shopping-microservices:grpc-server.adoc#_server[gRPC server] using {akka-http}[Akka HTTP] {akka-http}[{tab-icon}, window="tab"] and {akka-grpc}[Akka gRPC] {akka-grpc}[{tab-icon}, window="tab"]. That example, though, will only bind a server supporting plaintext HTTP.

Enabling TLS for gRPC doesn't differ from enabling TLS for other application protocols served over HTTP. You will need to follow these 3 steps:

. obtain a certificate
. create an `HttpsConnectionContext`
. setup the `Http` instance to use the `HttpsConnectionContext`

Follow the {akka-http}/server-side/server-https-support.html[Akka HTTP documentation] for details on each of those steps.

Note that since gRPC requires HTTP/2, when you enable TLS for gRPC you also need to support https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation[Application-Layer Protocol Negotiation (ALPN)] to negotiate whether both client and server support HTTP/2. The JVM provides ALPN support starting from JDK 8u252. Make sure you run a JVM greater than that.

NOTE: See also the documentation on {akka-http}/current/server-side/http2.html#use-newserverat-bind-and-https[using the `newServerAt(...).bind()` API when serving HTTPS].

== Consume gRPC services over TLS

When consuming a gRPC that's served over an encrypted (non `plaintext`) connection, you must setup the `GrpcClientSettings` to enable TLS and, optionally, reconfigure the `ssl-provider` if you want to fine tune what implementation to use. See the {akka-grpc}/client/configuration.html[documentation for gRPC Client Configuration] for all the details.

== Advanced configurations

If you want to {akka-http}/server-side/server-https-support.html#running-both-http-and-https[run both HTTP and HTTPS side by side] you must create two `Http` instances and bind each instance to a different port. Both instances should share a single `Route` instance.

