= Improve SBR's decision process

include::partial$include.adoc[]

Deploying on Kubernetes opens the door to use Kubernetes-provided mechanisms for decision-making. The Pekko {pekko}/split-brain-resolver.html[Split-Brain Resolver {tab-icon}, window="tab"] can use a {pekko-management}/kubernetes-lease.html[Lease {tab-icon}, window="tab"] backed by Kubernetes to control  which side of a cluster may remain up during a split-brain scenario.

NOTE: This How-To guide assumes you are developing an application based on Pekko Cluster and already enabled and configured xref:concepts:pekko-cluster.adoc#_split_brain_resolver[Pekko Cluster's Split-Brain Resolver].

== Add the Kubernetes Lease dependency

First make sure your application includes the SBR and the Kubernetes Lease dependencies on the build:

[.tabset]
Java::
+
.pom.xml:
[source,xml,indent=0]
----
include::example$shopping-cart-service-java/pom.xml[tag=pekko-sbr-kubernetes-lease]
----

Scala::
+
.build.sbt:
[source,scala,indent=0]
----
include::example$shopping-cart-service-scala/build.sbt[tag=pekko-sbr-kubernetes-lease]
----

== Setup your Kubernetes Cluster and PekkoMicroservice

When xref:deployment:aws-install.adoc#_install_pekko_operator[installing the Pekko Operator] on your Kubernetes cluster using the Helm chart you will also install the Pekko Kubernetes Lease CRD.

Once the CRD is installed, you can configure your Pekko Microservice to back the SBR implementation with a Kubernetes Lease enabling it on the PekkoMicroservice CR:

.kubernetes/shopping-cart-service-cr.yml
[source,yaml]
----
apiVersion: pekko.apache.org/v1
kind: PekkoMicroservice
metadata:
  name: shopping-cart-service
spec:
  image: <image>
  splitBrainResolver:
    useKubernetesLease: true # <1>

----

<1> When using a kubernetes lease as a backend for the Split-Brain Resolver, the operator will name the lease `<metadata.name>-pekko-sbr`. In the example above, the lease will be named `shopping-cart-service-pekko-sbr`.
