= Implementing Microservices with Akka
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

include::ROOT:partial$include.adoc[]

This example illustrates how multiple microservices can interact to implement a system. They use Akka Persistence for Event Sourcing and Akka Projections to implement CQRS for the event-sourced entities.

== Tutorial

This example evolves around a shopping cart. The tutorial takes you through the following steps to build the services from scratch, and adding piece by piece with deployment to the cloud for each step.

. xref:overview.adoc[Overview of the example]
. xref:dev-env.adoc[Development environment]
. xref:grpc-server.adoc[First gRPC service]
. xref:entity.adoc[Event Sourced entity]
. xref:complete-entity.adoc[Complete Event Sourced entity]
. xref:projection-query.adoc[Projection for queries]
. xref:projection-kafka.adoc[Projection publishing to Kafka]
. xref:projection-grpc-client.adoc[Projection calling gRPC service]

== Dependencies

This example project uses

- {akka}/typed/cluster-sharding.html[Akka Cluster Sharding] {akka}/typed/cluster-sharding.html[{tab-icon}, window="tab"] to distribute processing
- {akka-persistence-cassandra}/[Akka Persistence Cassandra] {akka-persistence-cassandra}/[{tab-icon}, window="tab"] to use Event Sourcing
- {akka-projection}/[Akka Projections] {akka-projection}/[{tab-icon}, window="tab"] to enable CQRS
- {akka-grpc}/[Akka gRPC] {akka-grpc}/[{tab-icon}, window="tab"] to implement a gRPC service API
- {akka-management}/[Akka Management] {akka-management}/[{tab-icon}, window="tab"] for health checks

The exact dependencies are shown below:

[.tabset]
sbt::
+
--
[source,scala]
----
include::example$shopping-cart-service-scala/build.sbt[tag=libraryDependencies]
----
--

Akka gRPC requires an sbt plugin.

[.tabset]
sbt::
+
--
[source,scala]
----
include::example$shopping-cart-service-scala/project/plugins.sbt[tag=libraryDependencies]
----
--


