= Implementing Event sourcing and CQRS with Akka
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

include::ROOT:partial$include.adoc[]

This example illustrates how multiple small microservices can interact to implement a system. They use Akka Persistence to enables Event sourcing and Akka Projection to implement CQRS for the event-sourced entities.

== Tutorial

This example evolves around a shopping cart. The tutorial takes you through the following steps to build the services from scratch, and adding piece by piece with deployment to the cloud for each step.

. xref:tutorial/dev-env.adoc[Development environment]
. xref:tutorial/overview.adoc[Overview of the example]
. xref:tutorial/grpc-server.adoc[First gRPC service]
. xref:tutorial/entity.adoc[Event Sourced entity]
. xref:tutorial/complete-entity.adoc[Complete Event Sourced entity]
. xref:tutorial/projection-query.adoc[Projection for queries]
. xref:tutorial/projection-kafka.adoc[Projection publishing to Kafka]
. xref:tutorial/projection-grpc-client.adoc[Projection calling gRPC service]

== Dependencies

This example project uses

- link:{akka}/typed/cluster-sharding.html[Akka Cluster Sharding]
- link:{akka-persistence-cassandra}/[Akka Persistence Cassandra]
- link:{akka-projection}/[Akka Projection]
- link:{akka-grpc}/[Akka gRPC]

The exact dependencies are shown below:

[.tabset]
sbt::
+
--
[source,scala]
----
include::example$shopping-cart-service-scala/build.sbt[tag=libraryDependencies]
----
--

[.tabset]
sbt::
+
--
[source,scala]
----
include::example$shopping-cart-service-scala/project/plugins.sbt[tag=libraryDependencies]
----
--


