= Implementing Event sourcing and CQRS with Akka
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

include::ROOT:partial$include.adoc[]

This example illustrates how Akka Persistence enables Event sourcing and how Akka Projection simplifies CQRS for the event-sourced entities.

== Video walk-throughs

An eight-minute video demonstrating how to use Event Sourcing in Akka 2.6.

Sample code from the Akka CQRS example project (Java or Scala). Including how to integrate with Cluster Sharding and Akka HTTP.

link:https://www.youtube.com/watch?v=xWuOGqmR7ow[Watch on YouTube,role=yt-widget]

This short video illustrates how to implement Command Query Responsibility Segregation (CQRS) with Akka 2.6. CQRS is a pattern for decoupling write operations from read operations.

link:https://www.youtube.com/watch?v=6ECsFlNNIAM[Watch on YouTube ,role=yt-widget]


== Example scenario

This example evolves around a shopping cart to collect items a user is selecting and create an order of the items currently in the shopping cart. The shopping cart contents are persisted by xref:cqrs:event-sourcing.adoc[Event Sourcing] from the commands that make updates to the carts. The events are persisted to a Cassandra database as an "Event Journal".

The service counts how often an item is added to any shopping cart to get a measure of popularity. This information is derived or "projected" from the contents of all shopping carts. Projecting data into a new representation from commands that update an Event Journal is supported by link:{akka-projection}/[Akka Projection]. This idea of creating a dependent projection of data is part of Command Query Responsibility Segregation (or CQRS).


== Dependencies

This example project uses

- link:{akka}/typed/cluster-sharding.html[Akka Cluster Sharding]
- link:{akka-persistence-cassandra}/[Akka Persistence Cassandra]
- link:{akka-projection}/[Akka Projection]
- link:{akka-grpc}/[Akka gRPC]

The exact dependencies are shown below:

[.tabset]
sbt::
+
--
[source,scala]
----
include::example$shopping-cart-service-scala/build.sbt[tag=libraryDependencies]
----
--

[.tabset]
sbt::
+
--
[source,scala]
----
include::example$shopping-cart-service-scala/project/plugins.sbt[tag=libraryDependencies]
----
--


