= Implementing Event sourcing and CQRS with Akka
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

include::ROOT:partial$include.adoc[]

This example illustrates how Akka Persistence enables Event sourcing and how Akka Projection simplifies CQRS for the event-sourced entities.

== Video walk-throughs

An eight minute video demonstrating how to use Event Sourcing in Akka 2.6.

Sample code from the Akka CQRS example project (Java or Scala). Including how to integrate with Cluster Sharding and Akka HTTP.

link:https://www.youtube.com/watch?v=xWuOGqmR7ow[Watch on YouTube,role=yt-widget]

This short video illustrates how to implement CQRS with Akka 2.6. CQRS is a pattern for decoupling write operations from read operations.

link:https://www.youtube.com/watch?v=6ECsFlNNIAM[Watch on YouTube ,role=yt-widget]

== Dependencies

This example project uses

- link:https://doc.akka.io/docs/akka/current/typed/cluster-sharding.html[Akka Cluster Sharding]
- link:https://doc.akka.io/docs/akka-persistence-cassandra/current/[Akka Persistence Cassandra]
- link:https://doc.akka.io/docs/akka-projection/current/[Akka Projection]
- link:https://doc.akka.io/docs/akka-http/current/[Akka HTTP]

The exact dependencies are shown below:

[.tabset]
sbt::
+
--
[source,scala]
----
include::example$akka-sample-cqrs-scala/build.sbt[tag=libraryDependencies]
----
--
Maven::
+
--
[source,xml]
----
include::example$akka-sample-cqrs-java/pom.xml[tag=dependencies]
----
--

