= I: Set up your development environment

include::ROOT:partial$include.adoc[]


To follow tutorial steps you will need a code editor, a build tool, and `grpcurl` (a CLI for sending gRPC calls). You can use your preferred code editor. We provide the steps for using https://www.jetbrains.com/idea/[IntelliJ IDEA {tab-icon}, window="tab"] from JetBrains. For the Scala version of the example, we use `sbt` as the build tool. 

This tutorial uses Cassandra and Kafka. You may run local installations during development, but we recommend running both services using https://docs.docker.com[Docker {tab-icon}, window="tab"]. The template project's root directory includes a https://docs.docker.com/compose/[Docker Compose] https://docs.docker.com/compose/[{tab-icon}, window="tab"] file that you can use to run Cassandra and Kafka. The provided Docker Compose file also runs Zookeeper which is required to run a Kafka broker.

The following sections provide links for downloading and installing:

* <<IntelliJ IDEA>>
* <<The sbt tool>>
* <<The grpcurl tool>>
* <<Docker and Docker Compose>>

We also provide downloadable versions of the example at different phases of completion. And, you will likely want to test locally before deploying to the cloud. You will need to understand how to configure to run locally. The following sections provide information on:

* <<Downloadable example source>>
* <<Configuring for local development>>
 

:!sectnums:
== IntelliJ IDEA

To install IntelliJ and prepare to develop the Scala example, follow these steps:
 
. Download and install https://www.jetbrains.com/idea/download/[IntelliJ {tab-icon}, window="tab"].
. From the *Preferences* menu, add the *Scala* plugin.

== The sbt tool

For the Scala Shopping Cart example, we use `sbt` as the build tool. https://www.scala-sbt.org/download.html[Install sbt] if you haven't already.

[TIP]
====
`sbt` is an interactive shell. If you start it with the `sbt` command, you can repeatedly run tasks like `compile` and `test` in the sbt shell. In the tutorial we use the full command for clarity, such as `sbt compile`. You can run tasks independently in this way, but it's faster to leave the `sbt` shell running and only enter the tasks. For example:

----
$ sbt
...
sbt:shopping-cart-service> compile
...
sbt:shopping-cart-service> test
...
----
====

== The grpcurl tool

The https://github.com/fullstorydev/grpcurl[grpcurl {tab-icon}, window="tab"] tool is useful for making gRPC calls from the command line. It is used in tutorial procedures and we recommend that you install it as described in https://github.com/fullstorydev/grpcurl#installation[the grpcurl documentation {tab-icon}, window="tab"].

== Docker and Docker Compose
[#docker]

See the instructions for installing https://docs.docker.com/get-docker/[Docker {tab-icon}, window="new"] and https://docs.docker.com/compose/install/[Docker Compose {tab-icon}, window="tab"] on your platform. 

== Downloadable example source

We encourage entering the code described in the tutorial, even if you just copy and paste. If you get stuck or prefer to skip over some parts you can download a zip file containing the complete source code for each part of the tutorial.

ifdef::todo[TODO: download link]

ifdef::review[REVIEWERS: in the new UI template that we will have soon, each page will have a next and previous link with the full page title. The Learn More section can still appear but it makes sense for it not to include the next page.]

== Configuring for local development

ifdef::review[REVIEWERS: I was not sure whether this section belongs here or where they actually will need to use it. I found the following confusing, it says that the template includes the config for running locally, but then in sentence #3, it says when running locally, some config properties must be overridden? Then it says those properties "are placed" in the file, by whom? Are they there or do I need to put them there? I'll find out when I try, but just wanted to point out that this is confusing.]

The template project comes with configuration for running the application locally. By default, when using `sbt run` the `Main` class will start an `ActorSystem` with the default `application.conf`. When running locally some configuration properties must be overridden. Those local configuration properties are placed in the `local1.conf` file and you can run the application with this configuration with:

[source,shell script]
----
sbt -Dconfig.resource=local1.conf run
----

The `local1.conf` includes the `application.conf`. There are also `local2.conf`, `local3.conf`, and so on. Those define settings for additional Akka Cluster nodes. For example, a second node can be started with:

[source,shell script]
----
sbt -Dconfig.resource=local2.conf run
----

When you develop several services you have to adjust the port numbers in those files. Each node (`ActorSystem`) must use unique ports when running several on the same machine.


The example projects are using the following ports.

.shopping-cart-service ports
|===
|Node |Akka Cluster |Akka Management HTTP |Akka gRPC

|local1.conf
|2551
|9101
|8101

|local2.conf
|2552
|9102
|8102

|local3.conf
|2553
|9103
|8103

|===

.shopping-analytics-service ports
|===
|Node |Akka Cluster |Akka Management HTTP |Akka gRPC

|local1.conf
|3551
|9201
|-

|local2.conf
|3552
|9202
|-

|local3.conf
|3553
|9203
|-

|===

.shopping-order-service ports
|===
|Node |Akka Cluster |Akka Management HTTP |Akka gRPC

|local1.conf
|4551
|9301
|8301

|local2.conf
|4552
|9302
|8302

|local3.conf
|4553
|9303
|8303

|===


== Learn more

* Next, xref:template.adoc[get your project] set up.
* Revisit the overview in xref:overview.adoc[previous step].
