= Implementing Microservices with Akka

include::ROOT:partial$include.adoc[]

This tutorial illustrates how Microservices can interact to implement a shopping cart system. The sections listed below show how to build the services piece by piece, from scratch.

include::partial$listing.adoc[]

== Learn more

The following links provide more information about some of the Akka Platform features used in the tutorial.

* {akka}/typed/cluster-sharding.html[Akka Cluster Sharding {tab-icon}, window="tab"] to distribute Event Sourced cart entities and Projections
* {akka}/typed/persistence.html[Akka Event Sourcing {tab-icon}, window="tab"] to store the state of the shopping carts
* {akka-projection}/[Akka Projections {tab-icon}, window="tab"] to enable CQRS and event based communication with other services
* {akka-grpc}/[Akka gRPC {tab-icon}, window="tab"] to implement a gRPC service API and communication with other services
* {akka-management}/[Akka Management {tab-icon}, window="tab"] for Akka Cluster formation and health checks
* xref:deployment:index.adoc[Kubernetes deployment with the Akka Operator]

=== Akka Workshop
In addition to the above resources there is the video based https://info.lightbend.com/akka-platform-workshop-part-1-on-demand-recording.html[Akka Workshop Series {tab-icon}, window="tab"]. The series will walk you through the basics of using the Akka Platform in parallel with much of the material in this guide. It should be especially useful for individuals who are audio/visual learners.