= Implementing Microservices with Pekko

include::ROOT:partial$include.adoc[]

This tutorial illustrates how Microservices can interact to implement a shopping cart system. The sections listed below show how to build the services piece by piece, from scratch.

include::partial$listing.adoc[]

== Learn more

The following links provide more information about some of the Pekko Platform features used in the tutorial.

* {pekko}/typed/cluster-sharding.html[Pekko Cluster Sharding {tab-icon}, window="tab"] to distribute Event Sourced cart entities and Projections
* {pekko}/typed/persistence.html[Pekko Event Sourcing {tab-icon}, window="tab"] to store the state of the shopping carts
* {pekko-projection}/[Pekko Projections {tab-icon}, window="tab"] to enable CQRS and event based communication with other services
* {pekko-grpc}/[Pekko gRPC {tab-icon}, window="tab"] to implement a gRPC service API and communication with other services
* {pekko-management}/[Pekko Management {tab-icon}, window="tab"] for Pekko Cluster formation and health checks
* xref:deployment:index.adoc[Kubernetes deployment with the Pekko Operator]

=== Pekko Workshop
In addition to the above resources there is the video based https://info.lightbend.com/pekko-platform-workshop-part-1-on-demand-recording.html[Pekko Workshop Series {tab-icon}, window="tab"]. The series will walk you through the basics of using the Pekko Platform in parallel with much of the material in this guide. It should be especially useful for individuals who are audio/visual learners.