= Part 3: First gRPC service
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

include::ROOT:partial$include.adoc[]

In this part we will create the `ShoppingCartService` with gRPC. At first it will only have one operation to add items to a cart. It will be a dummy implementation that is only logging the calls. In later parts of the tutorial it will be expanded with more operations and real implementations.

You will learn how to:

* define the interface of the gRPC service
* implement the service interface
* initialize and run the server
* interact with the service from the command line
* deploy for the first time to the cloud

TODO link to gRPC concepts

== Service definition

First you should define the interface of the service in a protobuf service descriptor. It should be located in the `src/main/protobuf/ShoppingCartService.proto`.

TODO proto

== Generate code

From the service descriptor source code will be generated by the Akka gRPC plugin when you compile the project.

----
sbt compile
----

== Service implementation

Let's implement the `ShoppingCart` trait. Create a `ShoppingCartServiceImpl` class that extends the generated `ShoppingCartService` trait. Implement the `addItem` method from the trait by logging the call and return a successful `Future`.

TODO ShoppingCartServiceImpl code

== Server

The service implementation is running by an Akka HTTP server. Add the following server initialization code in a `ShoppingCartServer` object.

[source,scala]
----
include::example$shopping-cart-service-scala/src/main/scala/sample/shoppingcart/ShoppingCart.scala[]
----

== Main

To run the service as a Java application we need a class with a `main` method. Add a `Main` class that is initializing the `ActorSystem` and the `ShoppingCartServer` like this:

TODO Main code

== Run

You can run this service with:

----
sbt "runMain sample.shoppingcart.Main 2551"
----

Note the log output from the `ShoppingCartServer`

----
Shopping online at gRPC server 127.0.0.1:8051
----

Try it with link:https://github.com/fullstorydev/grpcurl[grpcurl].

Add 3 socks to a cart:

----
grpcurl -d '{"cartId":"cart1", "itemId":"socks", "quantity":3}' -plaintext 127.0.0.1:8051 shoppingcart.ShoppingCartService.AddItem
----

Add 2 t-shirts to the same cart:

----
grpcurl -d '{"cartId":"cart1", "itemId":"t-shirt", "quantity":2}' -plaintext 127.0.0.1:8051 shoppingcart.ShoppingCartService.AddItem
----

Note the logging from the `ShoppingCartServiceImpl` in the console of the service.

You can stop the service with `ctrl-c`.

== Deploy

TODO deploy to cloud and try it
