apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "shopping"
---
apiVersion: pekko.apache.org/v1
kind: PekkoMicroservice
metadata:
  name: shopping-cart-service
  namespace: "shopping"
spec:
  replicas: 1
  image: <docker-registry>/shopping-cart-service:<tag>
  javaOptions: "-Xlog:gc -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
  resources:
    limits:
      memory: "2Gi"
    requests:
      memory: "2Gi"
      cpu: "1"
  cassandraDataStaxAstra:
    credentialsSecret: shopping-cart-service-astra-secret
  kafka:
    credentialsSecret: shopping-cart-service-kafka-secret
