= AWS X-Ray Tracing support
:page-toclevels: 3

include::ROOT:partial$include.adoc[]

Lightbend Telemetry 2.16.1+ can report traces to https://aws.amazon.com/xray/[AWS X-Ray {tab-icon}, window="tab"] using the https://aws-otel.github.io/[AWS Distro {tab-icon}, window="tab"] and the {cinnamon-docs}/extensions/opentracing/zipkin.html[Zipkin reporter {tab-icon}, window="tab"].

Note that Lightbend Telemetry doesn't send traces directly to AWS X-Ray. You will need to set up the https://github.com/aws-observability/aws-otel-Collector[AWS OTel Collector {tab-icon}, window="tab"] within your EKS cluster. Lightbend Telemetry uses Zipkin protocol to send traces to the AWS OTel Collector that batches and pushes them to the AWS X-Ray backend.

First, you will need to install AWS OTel Collector into your EKS cluster. We provide a Pulumi script that automates EKS cluster and Akka Operator setup. It also has an option to install AWS OTel Collector. Please follow instructions on the xref:deployment:aws-install-quickstart.adoc#install-aws-otel-collector[AWS OTel Collector] page.

Once you have the AWS OTel Collector deployed you will need to configure your application.

In order to enable your application to produce traces, you will need to set up Cinnamon agent as described on the {cinnamon-docs}/getting-started/start.html[Lightbend Telemetry Getting started {tab-icon}, window="tab"] page.

After that, you will need to add tracing-specific configuration and dependencies.

The following is the core Cinnamon and Zipkin reporter dependencies that you will need to add to your build tool configuration:

[.tabset]
Java::
+
.pom.xml
[source,xml,indent=0]
----
include::example$telemetry-sample/pom.xml[tag=telemetry-opentracing-dependencies]
----

Scala::
+
.build.sbt
[source,scala,indent=0]
----
include::example$telemetry-sample/build.sbt[tag=telemetry-opentracing-dependencies]
----

After you have made that alteration, enable {cinnamon-docs}/extensions/opentracing/xray.html[Lightbend Telemetry X-Ray support {tab-icon}, window="tab"] (only available in Lightbend Telemetry 2.16.1+) and configure Zipkin reporter to send traces to the AWS OTel Collector:

.src/main/resources/telemetry.conf
[source,hocon]
----
include::example$telemetry-sample/src/main/resources/telemetry.conf[tag=tracing-x-ray-support]
----

Lightbend Telemetry provides a wide variety of tracing options you can find in {cinnamon-docs}/extensions/opentracing/enabling.html#enabling-opentracing-in-your-app[the Lightbend Telemetry documentation {tab-icon}, window="tab"].

As an example you can use the next configuration to enable HTTP client and server tracing:

.src/main/resources/telemetry.conf
[source,hocon]
----
include::example$telemetry-sample/src/main/resources/telemetry.conf[tag=tracing-config-http]
----

Once the application is configured and deployed the traces will appear at the AWS X-Ray console.

