= Getting started
:page-toclevels: 3

include::ROOT:partial$include.adoc[]

Lightbend Telemetry can capture data for {akka-http}/introduction.html[Akka HTTP and Akka gRPC {tab-icon}, window="tab"] related features.

Lightbend provides two essential pieces for Monitoring your deployments; Telemetry (a.k.a. Cinnamon) and Lightbend Console. This documentation is focused solely on Telemetry. Telemetry makes it possible to gather metric, event and trace information from your applications. The information is transferred to various backends. The rest of this documentation provides an overview of Telemetry and explains how to get started, configure and run Telemetry in production.

:sectnums:

== Subscriptions and credentials

Use of lightbend Telemetry requires a subscription and credentials. A Lightbend subscription includes open source components that are distributed from the https://maven.apache.org/repository/[Maven Central Repository], as well as the commercial components which are distributed from a private repository. A https://www.lightbend.com/lightbend-platform-subscription[Lightbend Subscription] entitles you to use all commercial features and includes https://www.lightbend.com/lightbend-platform-subscription[support] and https://academy.lightbend.com/dashboard/[Lightbend Academy].

Telemetry is also available by subscription to the Akka Cloud Platform which is via {aws-marketplace}[Amazon Web Services (AWS) {tab-icon}, window="tab"] or {gcp-marketplace}[Google Cloud Platform (GCP) {tab-icon}].

Once you have a subscription, visit https://www.lightbend.com/account/lightbend-platform/credentials[lightbend.com] and login to learn how to add credentials to your development projects.


== Set up Cinnamon Agent

To get started, you should configure {cinnamon-docs}/setup/setup.html[your build {tab-icon}, window="tab"] to use the Cinnamon Agent for one of the following build systems: {cinnamon-docs}/setup/cinnamon-agent-sbt.html[sbt {tab-icon}, window="tab"], {cinnamon-docs}/setup/cinnamon-agent-maven.html[Maven {tab-icon}, window="tab"], or {cinnamon-docs}/setup/cinnamon-agent-gradle.html[Gradle {tab-icon}, window="tab"].

=== Maven build changes

To automatically pull down the agent as part of your build, you add the following plugin to download as part of the `package` task.

ifdef::todo[TODO: Externalize pom.xml configuration to a sample application?]

.pom.xml:
[source,xml,indent=0]
----
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-dependency-plugin</artifactId>
  <version>3.1.1</version>
  <executions>
    <execution>
      <id>copy</id>
      <phase>compile</phase>
      <goals>
        <goal>copy</goal>
      </goals>
      <configuration>
        <artifactItems>
          <artifactItem>
            <groupId>com.lightbend.cinnamon</groupId>
            <artifactId>cinnamon-agent</artifactId>
            <version>2.15.0</version>
            <overWrite>true</overWrite>
            <destFileName>cinnamon-agent.jar</destFileName>
          </artifactItem>
        </artifactItems>
      </configuration>
    </execution>
  </executions>
</plugin>
----

Next, the agent needs to be added as a java command-line option. The following is an example of how to add the agent for the `exec:exec` task:

.pom.xml
[source,xml]
----
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>exec-maven-plugin</artifactId>
  <version>1.6.0</version>
  <configuration>
    <executable>java</executable>
    <arguments>
      <argument>-classpath</argument>
      <classpath/>
      <argument>-javaagent:${project.build.directory}/dependency/cinnamon-agent.jar</argument>
      <argument>... your other arguments here ...</argument>
    </arguments>
  </configuration>
</plugin>
----

The {cinnamon-docs}/setup/cinnamon-agent-maven.html[Full Telemetry Documentation {tab-icon}, window="tab"] contains more details and a complete sample.

== Instrumenting your application

Lightbend Telemetry can capture data for {akka-http}/introduction.html[Akka HTTP and Akka gRPC {tab-icon}, window="tab"] related features. After adding the Cinnamon Agent as described above, make sure that you add the Cinnamon Akka HTTP module dependency to your build file:

.pom.xml
[source,xml]
----
<!-- Use Akka HTTP instrumentation -->
<dependency>
  <groupId>com.lightbend.cinnamon</groupId>
  <artifactId>cinnamon-akka-http_2.12</artifactId>
  <version>2.15.0</version>
</dependency>
<!-- Use Akka gRPC instrumentation -->
<dependency>
  <groupId>com.lightbend.cinnamon</groupId>
  <artifactId>cinnamon-akka-grpc_2.12</artifactId>
  <version>2.16.0-SNAPSHOT</version>
</dependency>
----

== Telemetry Configuration

A {cinnamon-docs}/instrumentations/akka-http/akka-http-configuration.html#example-configurations[simple configuration {tab-icon}, window="tab"] for your Akka HTTP server will match all paths, hosts and ports:

ifdef::todo[TODO: Externalize configuration snippets to a sample application?]

.src/main/resources/telemetry.conf
[source,hocon]
----
cinnamon.akka.http.servers {
  "*:*" {
    paths {
      "*" {
        metrics = on
      }
    }
  }
}
----

A similar configuration can be done for the client:

.src/main/resources/telemetry.conf
[source,hocon]
----
cinnamon.akka.http.clients {
  "*:*" {
    paths {
      "*" {
        metrics = on
      }
    }
  }
}
----

:!sectnums:
