= Getting started
:page-toclevels: 3
:page-supergroup-java-scala: Language

include::ROOT:partial$include.adoc[]

Lightbend Telemetry can capture data for {akka-http}/introduction.html[Akka HTTP and Akka gRPC {tab-icon}, window="tab"] related features.

Lightbend provides two essential pieces for Monitoring your deployments; Telemetry (a.k.a. Cinnamon) and Lightbend Console. This documentation is focused solely on Telemetry. Telemetry makes it possible to gather metric, event and trace information from your applications. The information is transferred to various backends. The rest of this documentation provides an overview of Telemetry and explains how to get started, configure and run Telemetry in production.

:sectnums:

== Subscriptions and credentials

Use of lightbend Telemetry requires a subscription and credentials. A Lightbend subscription includes open source components that are distributed from the https://maven.apache.org/repository/[Maven Central Repository], as well as the commercial components which are distributed from a private repository. A https://www.lightbend.com/lightbend-platform-subscription[Lightbend Subscription] entitles you to use all commercial features and includes https://www.lightbend.com/lightbend-platform-subscription[support] and https://academy.lightbend.com/dashboard/[Lightbend Academy].

Telemetry is also available by subscription to the Akka Cloud Platform which is via {aws-marketplace}[Amazon Web Services (AWS) {tab-icon}, window="tab"] or {gcp-marketplace}[Google Cloud Platform (GCP) {tab-icon}].

Once you have a subscription, visit https://www.lightbend.com/account/lightbend-platform/credentials[lightbend.com] and login to learn how to add credentials to your development projects.


== Set up Cinnamon Agent

To get started, you should configure {cinnamon-docs}/setup/setup.html[your build {tab-icon}, window="tab"] to use the Cinnamon Agent for one of the following build systems: {cinnamon-docs}/setup/cinnamon-agent-sbt.html[sbt {tab-icon}, window="tab"], {cinnamon-docs}/setup/cinnamon-agent-maven.html[Maven {tab-icon}, window="tab"], or {cinnamon-docs}/setup/cinnamon-agent-gradle.html[Gradle {tab-icon}, window="tab"].

=== Commercial Repositories

Here we assume that you have the repositories configured as environment variables that can be read by your build tool:

[source,shell script]
----
export LIGHTBEND_COMMERCIAL_MVN=https://repo.lightbend.com/...
export LIGHTBEND_COMMERCIAL_IVY=https://repo.lightbend.com/...
----

These values will be later read by your build tool.

[.tabset]
Java::
+
.pom.xml
[source,xml,indent=0]
----
include::example$telemetry-sample/pom.xml[tag=telemetry-commercial-repository]
----

=== Build Properties

Let's define some version properties that will be reused later in multiple places of the build.

[.tabset]
Java::
+
.pom.xml
[source,xml,indent=0]
----
include::example$telemetry-sample/pom.xml[tag=telemetry-build-properties]
----

The {cinnamon-docs}/setup/cinnamon-agent-maven.html[Full Telemetry Documentation {tab-icon}, window="tab"] contains more details and a complete sample.

=== Instrumenting your application

Lightbend Telemetry can capture data for {akka-http}/introduction.html[Akka HTTP and Akka gRPC {tab-icon}, window="tab"] related features. After adding the Cinnamon Agent as described above, make sure that you add the Cinnamon Akka HTTP module dependency to your build file:

[.tabset]
Java::
+
.pom.xml
[source,xml,indent=0]
----
include::example$telemetry-sample/pom.xml[tag=telemetry-dependencies]
----

The {cinnamon-docs}/instrumentations/instrumentations.html[Telemetry Documentation {tab-icon}, window="tab"] contains full list of available instrumentations.

=== Run the application using Cinnamon Agent

Configure your build tool to use the agent.

[.tabset]
Java::
+
.pom.xml
[source,xml,indent=0]
----
include::example$telemetry-sample/pom.xml[tag=telemetry-agent-copy]
----

Next, the agent needs to be added as a java command-line option. The following is an example of how to use the agent when running the application locally:

[.tabset]
Java::
+
.pom.xml
[source,xml,indent=0]
----
include::example$telemetry-sample/pom.xml[tag=telemetry-javaagent-run]
----

You can optionally use the agent when running tests.

[.tabset]
Java::
+
.pom.xml
[source,xml,indent=0]
----
include::example$telemetry-sample/pom.xml[tag=telemetry-javaagent-test]
----

And also to include the agent JAR file when generating Docker images.

[.tabset]
Java::
+
.pom.xml
[source,xml,indent=0]
----
include::example$telemetry-sample/pom.xml[tag=telemetry-javaagent-docker]
----

== Telemetry Configuration

Lightbend Telemetry supports a {cinnamon-docs}/plugins/chmetrics/reporters.html#reporters[reporter {tab-icon} window="tab"] that can be used to see the metrics locally in your terminal. 

.src/main/resources/telemetry.conf
[source,hocon]
----
include::example$telemetry-sample/src/main/resources/telemetry.conf[tag=telemetry-config-console]
----

A {cinnamon-docs}/instrumentations/akka-http/akka-http-configuration.html#example-configurations[simple configuration {tab-icon}, window="tab"] for your Akka HTTP server will match all paths, hosts and ports:

.src/main/resources/telemetry.conf
[source,hocon]
----
include::example$telemetry-sample/src/main/resources/telemetry.conf[tag=telemetry-config-http-server]
----

A similar configuration can be done for the client:

.src/main/resources/telemetry.conf
[source,hocon]
----
include::example$telemetry-sample/src/main/resources/telemetry.conf[tag=telemetry-config-http-client]
----

:!sectnums:
