= Lightbend Telemetry Platform Guide
:page-toclevels: 3

include::ROOT:partial$include.adoc[]

Distributed systems are complex and have many moving parts, much of which are asynchronous and run in parallel. When building complex systems, it is best to consider design in small chunks that are composable. Instrumenting complex systems is no different. Lightbend Telemetry breaks capture down into composable parts that will provide better insight into your system. This section of the Akka Platform Guide is designed to get you started with a minimum telemetry deployment.

== About Lightbend Telemetry

Telemetry is a suite of tools that provide a view into your distributed platforms' internals. This view allows developers and operations to respond quickly to problems, track down unexpected behavior, and even tune your system. As a result, you can deploy your applications to production with confidence.

Telemetry makes it possible to gather metrics, events, and trace information from Akka, Scala, Play, and Lagom based applications, and then store such data in {cinnamon-docs}/introduction/introduction.html#backend-plugins[a metrics backend {tab-icon}, window="tab"] such as Prometheus. It collects runtime-information about your application using an agent that {cinnamon-docs}/introduction/introduction.html#instrumentations[instruments your code {tab-icon}, window="tab"] and can be configured to tailor the application needs.
