= Using Prometheus as the metrics backend
:page-toclevels: 3

include::ROOT:partial$include.adoc[]

Lightbend Telemetry can report metrics to https://prometheus.io/[Prometheus] using a backend plugin integrated with the https://github.com/prometheus/client_java[Prometheus JVM client].

Here is the core Cinnamon Prometheus dependency you need to add to your `pom.xml` together with the {cinnamon-docs}/plugins/prometheus/prometheus.html#http-server[HTTP server exporter]:

```xml
<!-- Cinnamon Prometheus core dependency -->
<dependency>
    <groupId>com.lightbend.cinnamon</groupId>
    <artifactId>cinnamon-prometheus</artifactId>
    <version>2.15.0</version>
</dependency>
<!-- Cinnamon Prometheus HTTP server dependency -->
<dependency>
    <groupId>com.lightbend.cinnamon</groupId>
    <artifactId>cinnamon-prometheus-httpserver</artifactId>
    <version>2.15.0</version>
</dependency>
```

After that, enable the HTTP server exporter using the following configuration:

```conf
cinnamon.prometheus {
  exporters += http-server
}
```

Prometheus metrics will now be available at the configured server location. Using the defaults, this is at http://localhost:9001/metrics.

See {cinnamon-docs}/plugins/prometheus/prometheus.html[our docs for more details and reference configuration].

ifdef::todo[TODO: Support has a signup process that will get AWS customers Lightbend credentials to download commercial dependencies.]