= Using Prometheus as the metrics backend
:page-toclevels: 3

include::ROOT:partial$include.adoc[]

Lightbend Telemetry can report metrics to https://prometheus.io/[Prometheus {tab-icon}, window="tab"] using a backend plugin integrated with the https://github.com/prometheus/client_java[Prometheus JVM client {tab-icon}, window="tab"].

The following is the core Cinnamon Prometheus dependency that you will need to add to your `pom.xml`, together with the {cinnamon-docs}/plugins/prometheus/prometheus.html#http-server[HTTP server exporter {tab-icon}, window="tab"]:

.pom.xml
[source,xml]
----
<!-- Cinnamon Prometheus core dependency -->
<dependency>
    <groupId>com.lightbend.cinnamon</groupId>
    <artifactId>cinnamon-prometheus</artifactId>
    <version>2.15.0</version>
</dependency>
<!-- Cinnamon Prometheus HTTP server dependency -->
<dependency>
    <groupId>com.lightbend.cinnamon</groupId>
    <artifactId>cinnamon-prometheus-httpserver</artifactId>
    <version>2.15.0</version>
</dependency>
----

After you have made that alteration, enable the HTTP server exporter using the following configuration:

.src/main/resources/telemetry.conf
[source,hocon]
cinnamon.prometheus {
  exporters += http-server
}
----

Metrics from Prometheus will now be available at the configured server location. If you are using the defaults, the location is http://localhost:9001/metrics.

See the {cinnamon-docs}/plugins/prometheus/prometheus.html[Full Telemetry documentation  {tab-icon}, window="tab"] for  details and references regarding Prometheus configuration.

